version: '3.9'
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
  voicevox_engine:
    container_name: voicevox_engine
    restart: always
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    tty: true
    ports:
      - "50021:50021"
volumes:
  node_modules:
